[Add]:Header component
OpenMined/pygrid-admin pull request #28
Opened 2021-02-21 11:23 UTC by infern018

## Description
Closes #27 
Added the header(navbar) component for each route in the index.txt file with proper functionality and routing of each section/subsection, also currently I was not able to add the adequate CSS as there were some problems in linking the global CSS file, so for mobile view CSS is not accurate, for desktop it is set correctly...

## Screenshots
![Screenshot (374)](https://user-images.githubusercontent.com/52378712/108623417-fc194c00-7464-11eb-821f-b1ad6b40be2e.png)
![Screenshot (375)](https://user-images.githubusercontent.com/52378712/108623420-ff143c80-7464-11eb-8230-cdb4f09298ff.png)
![Screenshot (376)](https://user-images.githubusercontent.com/52378712/108623424-01769680-7465-11eb-98a2-f6d78abef41f.png)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2021-02-21 11:23 UTC, infern018 commented
@tcp  pls review!

2021-02-22 06:21 UTC, infern018 commented
I've resolved the conflicts now, can you have a look and tell if me there should be any changes @tcp ?

2021-02-24 07:08 UTC, infern018 commented
I have fixed some UI components and made the header responsive.

## Screenshots:
<img width="202" alt="ad1" src="https://user-images.githubusercontent.com/52378712/108961253-13427e80-769d-11eb-9cf0-8b49edf95a6b.png">
<img width="202" alt="ad2" src="https://user-images.githubusercontent.com/52378712/108961364-3ec56900-769d-11eb-947f-0e2e38c0e955.png">

2021-02-26 01:05 UTC, tcp requested changes
Thank you for your submission!

I've left a few comments. Please don't forget to lint and format your code following the project settings.

Feel free to push a revised PR. Take care!

2021-02-26 01:05 UTC, tcp commented on src/components/header/index.tsx
> +        <div className="container w-full md:w-auto md:flex flex-row">
The header width follows the rest of the app. Changing to `w-full` and `w-auto` affects this behaviour.

2021-02-26 01:05 UTC, tcp commented on src/components/header/index.tsx
> +        var route_name = route.charAt(0).toUpperCase() + route.slice(1);
Use the `text-transform: capitalize` property instead. In tailwind, the class is `capitalize`.

2021-02-26 13:15 UTC, infern018 commented on src/components/header/index.tsx
> +        document.getElementById("hamburger").onclick = function toggleMenu() {
Hey Thiago, had a doubt here, I will need to manipulate the DOM as I want to add that hamburger menu functionality which involves the toggle of navbar in the mobile-view,

2021-02-26 13:24 UTC, tcp commented on src/components/header/index.tsx
> +        document.getElementById("hamburger").onclick = function toggleMenu() {
Hey @infern018! You should use the attributes, but like this:
```js
  <Hamburger onClick={open} />
```

Check out some info on React and the (virtual) DOM: [here](https://reactjs.org/docs/faq-internals.html), [here](https://reactjs.org/docs/rendering-elements.html) and [here](https://reactjs.org/docs/react-dom.html).

2021-02-26 13:30 UTC, infern018 commented on src/components/header/index.tsx
> +        document.getElementById("hamburger").onclick = function toggleMenu() {
I can make the `onclick` function work without using DOM, but for :
`const navToggle = **document.getElementsByClassName("toggle")**;`
          `for (let i = 0; i < navToggle.length; i++) {`
            `navToggle.item(i).classList.toggle("hidden");`
          `}`
  I will need to get access to the `toggle` class

2021-02-26 13:57 UTC, tcp commented on src/components/header/index.tsx
> +        document.getElementById("hamburger").onclick = function toggleMenu() {
One option is to use a state variable to keep track of this information.

```js
function Header() {
  ...
  const [isHidden, hide] = React.useState(true)
  const menuRef = React.useRef()
  ...
  <Hamburger ref={ref} onClick={() => hide(false)} />
  ...
}
```

You can use a hook for listening to clicks outside of the icon that would trigger the `() => hide(true)` to close the menu, for example.

2021-02-26 18:35 UTC, infern018 commented on src/components/header/index.tsx
> +            <img className="toggle block" src="https://img.icons8.com/fluent-systems-regular/2x/menu-squared-2.png" width={30} height={30} />
![image](https://user-images.githubusercontent.com/52378712/109340815-814e9780-788f-11eb-9bda-1cbd6db214ed.png)

Will SVG if this do?

2021-02-28 01:36 UTC, closed without merging