Users & Roles
OpenMined/pygrid-admin pull request #35
Opened 2021-02-24 14:27 UTC by hericlesme

## Description
Add users overview + list and roles page.

## Issues

#22 #15 

## Affected Dependencies
    "@reach/accordion": "^0.13.2"

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)

2021-02-25 01:47 UTC, ariannmichael approved these changes
Good work, the only additional point is in the future divide the interfaces on other files besides types/index.ts

2021-02-26 01:08 UTC, tcp commented on src/components/pages/users/cards/roles.tsx
> +  const permissions = [
Extract permissions out of the component. Maybe this could be in a JSON somewhere?

2021-02-26 01:15 UTC, tcp requested changes
Solid! Some minor changes needed. I'll see what it looks like!

2021-02-26 01:15 UTC, tcp commented on src/pages/users/index.tsx
> +  useEffect(() => {
I failed to see why we need to keep states to track the total. Is it possible to replace this effect with a direct call to each of the deps?

2021-02-26 13:09 UTC, tcp commented on src/pages/users/index.tsx
> +            {Object.keys(usersData).map(userId => (
`usersData` is undefined by default and will remain undefined if fetching fails.`isLoading` will resolve to `false` and `Object.keys(undefined)` throws.

2021-03-01 14:25 UTC, merged